# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16jiE2QwB2bFjiVjFsQWjLVE8398HvDGO
"""

from flask import Flask, render_template, request, redirect, url_for
import boto3
import os

app = Flask(__name__)
s3 = boto3.client('s3')
BUCKET_NAME = 'your-s3-bucket-name'  # replace with your actual bucket

@app.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        file = request.files['file']
        if file:
            s3.upload_fileobj(file, BUCKET_NAME, file.filename)
            return f"Uploaded: {file.filename}"
    return render_template('index.html')

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)